/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jpa.study;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;

public class App {
    public static void main(String[] args) {

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("H2");
        EntityManager em = emf.createEntityManager();

        EntityTransaction tx  = em.getTransaction();
        
        try {
            tx.begin();

            tx.commit();
        } catch (Exception e) {
            e.printStackTrace();
            tx.rollback();
        } finally{
            em.close();
        }
        emf.close();
    }
}
